### ISSUE TITLE
It should show what line the error happends

### ISSUE THREAD

**Issue by paladox** [brandonramirez/grunt-jsonlint#12]
It should show what line the error happends in the file and what it should be replaced with instead of just saying syntax error in this file.

**Comment by paladox** [comment]
See https://github.com/zaach/jsonlint/blob/master/lib/jsonlint.js

**Comment by brandonramirez** [comment]
Great suggestion!  A pull request is welcome if you're in a position to implement it, otherwise, I'll get to it soon.

**Comment by paladox** [comment]
Ok thanks I am not really good at js coding. I looked at it but was unsure on how to do it.

**Comment by brandonramirez** [comment]
The behavior you asked for seems to already be what this plugin does.

Here is an example JSON block:

        "listen": {
          "address": "0.0.0.0",
          "port": 8080
        }

If I intentionally remove the comma at the end of the `address` line, like so:

        "listen": {
          "address": "0.0.0.0"
          "port": 8080
        }

I get the following error:

    Running "jsonlint:appConfig" (jsonlint) task
    >> File "config/defaults.json" failed JSON validation.
    Warning: Parse error on line 8:
    ...s": "0.0.0.0"      "port": 8080    } 
    ----------------------^
    Expecting 'EOF', '}', ':', ',', ']', got 'STRING' Use --force to continue.

    Aborted due to warnings.

Line 8 corresponds to the line I described, but in my actual source file (I only included a partial).
