### ISSUE TITLE
Support finding what line and what file the error is from

### ISSUE THREAD

**Issue by paladox** [brandonramirez/grunt-jsonlint#17]
Hi please support finding what line the error comes from and what file it comes from please.

**Comment by paladox** [comment]
Maybe follow how https://github.com/gruntjs/grunt-contrib-jshint/tree/master/tasks is done since it finds the file and where the line should be changed.

**Comment by brandonramirez** [comment]
@paladox Can you pull down the latest version from the git master branch, try it out, and tell me if it fits your needs?

**Comment by brandonramirez** [comment]
Released to npm as version 1.0.7.

**Comment by paladox** [comment]
Thanks
