### ISSUE TITLE
add multiple formatters

### ISSUE THREAD

**Issue by HolgerJeromin** [brandonramirez/grunt-jsonlint#23]
After changing the error output to
`grunt.log.error(file + '(' + lastErrorLine + '): error:  failed JSON validation');`
Visual Studio [detects](https://msdn.microsoft.com/en-us/library/yxkt8b26.aspx) the line and allows clicking into it.
https://github.com/palantir/tslint has made it configurable with many formatters. 

BTW I would really love schema validation :-)

**Comment by brandonramirez** [comment]
Thanks, I will try this out shortly.  Sorry for the delay - been extremely busy.

**Comment by brandonramirez** [comment]
Created new issue #27 to track schema validation.

**Comment by brandonramirez** [comment]
@HolgerJeromin Can you take the latest code from the master branch and test it out in Visual Studio?  I updated the unit test to verify the output matches the format you describe, but I'm not in a position to actually test it against Visual Studio.

Thanks!
- Brandon

**Comment by brandonramirez** [comment]
@HolgerJeromin The default behavior in the master branch is restored to what it was, but you can add a grunt option to achieve the behavior you described.  I'd still like you to test it before I close this request out.

    jsonlint: {
      sample: {
        src: [ 'some/valid.json' ],
        options: {
          formatter: 'msbuild'
        }
      }
    }

**Comment by HolgerJeromin** [comment]
Sorry for my delay. I just tested the new version. Works nice. Thanks a lot!
