### ISSUE TITLE
Switch from using jsonlint from zaach/jsonlint to https://github.com/tmcw/jsonlint

### ISSUE THREAD

**Issue by paladox** [brandonramirez/grunt-jsonlint#25]
Reason since https://github.com/tmcw/jsonlint is newer is an updated version of jsonlint we use.

**Comment by brandonramirez** [comment]
Can you explain what is different or better about this jsonlint fork?

**Comment by brandonramirez** [comment]
@paladox I'll need specifics on what is different.  I'm definitely open to using a fork since the core `jsonlint` library today appears to be unmaintained.

**Comment by paladox** [comment]
Hes only done a few commits but heres some

https://github.com/tmcw/jsonlint/commit/90d177967e46313f62eaaa7262fcc500dbfee275

https://github.com/tmcw/jsonlint/commit/06f9b7a9a46bb27f952c303e9aa44a954ddee0b9

It is also a fork of zaach/jsonlint 

I carn't really say the difference but those two commits seem to be the bigger ones.

And we can always suggests improvements upstream in that fork.

**Comment by brandonramirez** [comment]
I switched to `jsonlint-lines`, which is from the github repo you pointed me to.  The error handling doesn't work correctly anymore.  I tried pointing directly at the repo as well and get the same results.

    virago:grunt-jsonlint brandon$ grunt jsonlint:invalid
    Running "jsonlint:invalid" (jsonlint) task
    >> File "test/invalid.json" failed JSON validation at line 9.
    Warning: Cannot read property '0' of undefined Use --force to continue.

    Aborted due to warnings.
    virago:grunt-jsonlint brandon$ 

What I get with the existing released code:

    virago:grunt-jsonlint brandon$ grunt jsonlint:invalid
    Running "jsonlint:invalid" (jsonlint) task
    >> File "test/invalid.json" failed JSON validation at line 9.
    Warning: Parse error on line 9:
    ...        "2"        "3",      ],      
    ----------------------^
    Expecting 'EOF', '}', ':', ',', ']', got 'STRING' Use --force to continue.

    Aborted due to warnings.
    virago:grunt-jsonlint brandon$

**Comment by brandonramirez** [comment]
This change breaks existing functionality, so not going to proceed.
