### ISSUE TITLE
v1.0.7 via npm

### ISSUE THREAD

**Issue by ehpc** [brandonramirez/grunt-jsonlint#26]
Hi!
I've tried to install your linter as a dep with **npm install grunt-jsonlint --save-dev**, but the installed version doesn't have a source code for formatting an output. Maybe you didn't update your npm?

**Comment by brandonramirez** [comment]
Right, I don't think the latest code is released.  I'll release it shortly.

**Comment by brandonramirez** [comment]
The versioning was a bit messed up.  1.0.7 was already released, but the feature you asked for was actually in 1.0.8.  I bumped the version and released 1.0.8 to npm.  Note dependency on node 4 and grunt 1.0 now.
