### ISSUE TITLE
Publish 1.1.0 release

### ISSUE THREAD

**Issue by paladox** [brandonramirez/grunt-jsonlint#28]
Hi please publish 1.1.0 release or is it going to be released at some time later please.

**Comment by brandonramirez** [comment]
It will be released soon.  I want to close out a few of the open issues first.  If you need it ASAP, I can release it as-is and move everything back to a v1.1.1.

**Comment by paladox** [comment]
Nope you can release it when ever you want not important to release it until you think it is an ok release to release.

**Comment by brandonramirez** [comment]
Scope complete and tests passing.  I'm updating documentation and will release to npm today.

**Comment by paladox** [comment]
Ok, thanks
