### ISSUE TITLE
Option to validate all files in directory

### ISSUE THREAD

**Issue by rewathkafley** [brandonramirez/grunt-jsonlint#29]
It would be good if there was an option to validate all files in a directory

**Comment by HolgerJeromin** [comment]
Did you tried this one?
```js
jsonlint: {
	sample: {
		src: [
			'./**/*.json'
		]
	}
},
```

**Comment by brandonramirez** [comment]
@HolgerJeromin is right - selecting which files to work on is handled by grunt.  A wildcard like @HolgerJeromin showed will work.
